FROM golang:alpine as builder
ARG src_dir

RUN apk --update --no-cache add git

RUN mkdir /builder
WORKDIR /builder
COPY . /builder

RUN cd /builder/mocker && go build

FROM alpine:latest

RUN apk update --no-cache && \
    adduser -S -D -H -h / flow
USER flow
COPY --from=builder /builder/mocker /

ENTRYPOINT ["./mocker"]
