{
 "title": "Karaf With nDPI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Device/Protocol/Port Debug Plane",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Device, Dest Port, Ndpi Proto, Ndpi Category",
   "type": "barchart",
   "description": "By 1 second",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flow_first_seen",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n     $timeSeries as t,\n\t  alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n    (sum(flow_src_packets_processed)+sum(flow_src_packets_processed)) as t_sum\nFROM $table\n\nWHERE $timeFilter and ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\n\nGROUP BY t, alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t\n",
     "rawQuery": "SELECT\n     (intDiv(toUInt32(flow_first_seen), 1) * 1) * 1000 as t,\n\t  alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n    (sum(flow_src_packets_processed)+sum(flow_src_packets_processed)) as t_sum\nFROM default.Flow\n\nWHERE flow_first_seen >= toDateTime(1671695332) AND flow_first_seen <= toDateTime(1671695632) and ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\n\nGROUP BY t, alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t",
     "round": "0s",
     "table": "Flow"
    }
   ]
  },
  {
   "title": "Device, Dest Port, Ndpi Proto, Ndpi Category",
   "type": "barchart",
   "description": "By 30 Second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flow_first_seen",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    hop(flow_first_seen, toIntervalSecond('30'), toIntervalSecond('30')) as t,\n\t  alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n    (sum(flow_src_packets_processed)+sum(flow_src_packets_processed)) as t_sum\nFROM $table\n\nWHERE $timeFilter and ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\n\nGROUP BY t, alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    hop(flow_first_seen, toIntervalSecond('30'), toIntervalSecond('30')) as t,\n\t  alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n    (sum(flow_src_packets_processed)+sum(flow_src_packets_processed)) as t_sum\nFROM default.Flow\n\nWHERE flow_first_seen >= toDateTime(1671695362) AND flow_first_seen <= toDateTime(1671695662) and ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\n\nGROUP BY t, alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t",
     "round": "0s",
     "table": "Flow"
    }
   ]
  },
  { "title": "Device Flow Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Device Flow Count(1 min)",
   "type": "barchart",
   "description": "source packet \n+\ndestination packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT\n    \n    hop((flow_first_seen  + interval 28800 second), toIntervalMinute('1'), toIntervalMinute('1')) AS t,\n    alias,\n    sum(flow_src_packets_processed) AS src,\n    sum(flow_dst_packets_processed) AS dst\nFROM Flow\nGROUP BY t, alias\norder by t desc limit 15\n",
     "rawQuery": "SELECT\n    \n    hop((flow_first_seen  + interval 28800 second), toIntervalMinute('1'), toIntervalMinute('1')) AS t,\n    alias,\n    sum(flow_src_packets_processed) AS src,\n    sum(flow_dst_packets_processed) AS dst\nFROM Flow\nGROUP BY t, alias\norder by t desc limit 15",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device Flow Count Top 20(60 min Stack)",
   "type": "barchart",
   "description": "source packet \n+\ndestination packet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flow_idle_time",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    hop((flow_first_seen + interval 28800 second), toIntervalMinute('60'), toIntervalMinute('60')) AS t,\n    alias,\n    sum(flow_src_packets_processed) AS src,\n    sum(flow_dst_packets_processed) AS dst\nFROM Flow\nGROUP BY t, alias\norder by t desc limit 20\n",
     "rawQuery": "SELECT\n    hop((flow_first_seen + interval 28800 second), toIntervalMinute('60'), toIntervalMinute('60')) AS t,\n    alias,\n    sum(flow_src_packets_processed) AS src,\n    sum(flow_dst_packets_processed) AS dst\nFROM Flow\nGROUP BY t, alias\norder by t desc limit 20",
     "round": "0s",
     "table": "Flow"
    }
   ]
  },
  {
   "title": "Each Device  Packet Count",
   "type": "timeseries",
   "description": "source packet \n+\ndestination packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "flow_first_seen",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SUM(CASE WHEN alias = 'manager' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as manager\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(flow_first_seen), 1) * 1) * 1000 as t,\n    SUM(CASE WHEN alias = 'manager' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as manager\nFROM default.Flow\n\nWHERE flow_first_seen >= toDateTime(1671686907) AND flow_first_seen <= toDateTime(1671687207)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "Flow"
    },
    {
     "database": "default",
     "dateTimeColDataType": "flow_first_seen",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SUM(CASE WHEN alias = 'mars_check' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as mars_check\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(flow_first_seen), 1) * 1) * 1000 as t,\n    SUM(CASE WHEN alias = 'mars_check' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as mars_check\nFROM default.Flow\n\nWHERE flow_first_seen >= toDateTime(1671686907) AND flow_first_seen <= toDateTime(1671687207)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "Flow"
    },
    {
     "database": "default",
     "dateTimeColDataType": "flow_first_seen",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    SUM(CASE WHEN alias = 'server01' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as server01\nFROM $table\n\nWHERE $timeFilter\n\nGROUP BY t\n\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(flow_first_seen), 1) * 1) * 1000 as t,\n    SUM(CASE WHEN alias = 'server01' THEN (flow_src_packets_processed+flow_src_packets_processed) else 0 END) as server01\nFROM default.Flow\n\nWHERE flow_first_seen >= toDateTime(1671686907) AND flow_first_seen <= toDateTime(1671687207)\n\nGROUP BY t\n\nORDER BY t",
     "round": "0s",
     "table": "Flow"
    }
   ]
  },
  { "title": "DPI Flow Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "title": "Device+Protocol+DPI(src+dst)", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 } },
  {
   "title": "Device+Dst Port+DPI Protocol and Category",
   "type": "bargauge",
   "description": "1: port != 0\n2:protocol not contain BIOS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "Select\n   alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n   (SUM(flow_src_packets_processed)+SUM(flow_dst_packets_processed)) t_sum\nFrom Flow\nwhere ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\nGROUP BY alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t_sum desc\n",
     "rawQuery": "Select\n   alias, toString(dst_port) as dst_p, ndpi_proto, ndpi_category,\n   (SUM(flow_src_packets_processed)+SUM(flow_dst_packets_processed)) t_sum\nFrom Flow\nwhere ndpi_proto NOT LIKE '%BIOS%' and dst_port != 0\nGROUP BY alias, dst_p, ndpi_proto, ndpi_category\n\nORDER BY t_sum desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device+Src_ip+DPI(src+dst)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n   alias, src_ip, ndpi_proto, (SUM(flow_src_packets_processed)+SUM(flow_dst_packets_processed)) t_sum\nFROM Flow\nGROUP BY alias, src_ip, ndpi_proto\nORDER BY t_sum desc\n\n",
     "rawQuery": "SELECT \n   alias, src_ip, ndpi_proto, (SUM(flow_src_packets_processed)+SUM(flow_dst_packets_processed)) t_sum\nFROM Flow\nGROUP BY alias, src_ip, ndpi_proto\nORDER BY t_sum desc",
     "round": "0s",
     "table": "Flow"
    }
   ]
  },
  {
   "title": "Device+5 tuple+DPI",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n alias, dst_ip, src_ip, l4_proto, toString(src_port) as src_p, toString(dst_port) as dst_p, ndpi_proto,\n (sum(flow_src_packets_processed) + sum(flow_dst_packets_processed)) as total_sum\nFROM Flow\nGROUP BY alias, dst_ip, src_ip, l4_proto, src_p , dst_p, ndpi_proto\nORDER BY total_sum desc limit 1000\n\n",
     "rawQuery": "SELECT\n alias, dst_ip, src_ip, l4_proto, toString(src_port) as src_p, toString(dst_port) as dst_p, ndpi_proto,\n (sum(flow_src_packets_processed) + sum(flow_dst_packets_processed)) as total_sum\nFROM Flow\nGROUP BY alias, dst_ip, src_ip, l4_proto, src_p , dst_p, ndpi_proto\nORDER BY total_sum desc limit 1000",
     "round": "0s"
    }
   ]
  },
  { "title": "DPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "IPV4 Src + DPI",
   "type": "piechart",
   "description": "By source packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    src_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY src_ip, ndpi_proto\n",
     "rawQuery": "SELECT\n    src_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY src_ip, ndpi_proto",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device + SIP + DPI",
   "type": "piechart",
   "description": "By source packet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    alias, src_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY alias, src_ip, ndpi_proto\n",
     "rawQuery": "SELECT\n    alias, src_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY alias, src_ip, ndpi_proto",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Devices+SIP+DIP+DPI",
   "type": "piechart",
   "description": "By Source Packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    alias, src_ip, dst_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY alias, src_ip, dst_ip, ndpi_proto\n\n",
     "rawQuery": "SELECT\n    alias, src_ip, dst_ip, ndpi_proto,\n    SUM(flow_src_packets_processed)\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY alias, src_ip, dst_ip, ndpi_proto",
     "round": "0s"
    }
   ]
  },
  { "title": "IP Flow Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "IPV4 Address",
   "type": "piechart",
   "description": "By Source Packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    src_ip, SUM(flow_src_packets_processed) as c\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY src_ip\norder by c desc\n",
     "rawQuery": "SELECT\n    src_ip, SUM(flow_src_packets_processed) as c\nFROM Flow\nWHERE src_ip LIKE ('%.%')\nGROUP BY src_ip\norder by c desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IPV4 Address",
   "type": "piechart",
   "description": "By Destination Packet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    dst_ip, (sum(flow_dst_packets_processed)) as c\nFROM Flow\nWHERE dst_ip LIKE ('%.%')\nGROUP BY dst_ip\norder by c desc\n",
     "rawQuery": "SELECT\n    dst_ip, (sum(flow_dst_packets_processed)) as c\nFROM Flow\nWHERE dst_ip LIKE ('%.%')\nGROUP BY dst_ip\norder by c desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IPV6 Address",
   "type": "piechart",
   "description": "By Source Packet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    src_ip, SUM(flow_src_packets_processed) as c\nFROM Flow\nWHERE src_ip LIKE ('%:%')\nGROUP BY src_ip\norder by c desc\n",
     "rawQuery": "SELECT\n    src_ip, SUM(flow_src_packets_processed) as c\nFROM Flow\nWHERE src_ip LIKE ('%:%')\nGROUP BY src_ip\norder by c desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IPV6 Address",
   "type": "piechart",
   "description": "By Destination Packet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    dst_ip, SUM(flow_dst_packets_processed)\nFROM Flow\nWHERE dst_ip LIKE ('%:%')\nGROUP BY dst_ip\n",
     "rawQuery": "SELECT\n    dst_ip, SUM(flow_dst_packets_processed)\nFROM Flow\nWHERE dst_ip LIKE ('%:%')\nGROUP BY dst_ip",
     "round": "0s"
    }
   ]
  },
  { "title": "5 tuple + DPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "5 tuple(Limit 1000)",
   "type": "table",
   "description": "Source Packet + Destination Packet",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 86 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n dst_ip, src_ip, l4_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (dst_sum+src_sum) as src_dst,\n Count(*) as total_sum\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port\nORDER BY src_dst desc limit 1000\n",
     "rawQuery": "SELECT\n dst_ip, src_ip, l4_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (dst_sum+src_sum) as src_dst,\n Count(*) as total_sum\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port\nORDER BY src_dst desc limit 1000",
     "round": "0s"
    }
   ]
  },
  {
   "title": "5 tuple(Top 100)",
   "type": "piechart",
   "description": "Source Packet + Destination Packet",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n dst_ip, src_ip, l4_proto, src_port, dst_port, Count(*) as total_sum,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (dst_sum+src_sum) as dst_src\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port\nORDER BY dst_src desc limit 1000",
     "rawQuery": "SELECT\n dst_ip, src_ip, l4_proto, src_port, dst_port, Count(*) as total_sum,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (dst_sum+src_sum) as dst_src\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port\nORDER BY dst_src desc limit 1000",
     "round": "0s"
    }
   ]
  },
  {
   "title": "5 tuple(DPI+Limit 1000)",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 94 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n dst_ip, src_ip, l4_proto, ndpi_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (src_sum+dst_sum) as src_dst,\n  Count(*) as total_sum\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port, ndpi_proto\nORDER BY src_dst desc limit 1000\n",
     "rawQuery": "SELECT\n dst_ip, src_ip, l4_proto, ndpi_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (src_sum+dst_sum) as src_dst,\n  Count(*) as total_sum\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, src_port , dst_port, ndpi_proto\nORDER BY src_dst desc limit 1000",
     "round": "0s"
    }
   ]
  },
  {
   "title": "5 tuple(DPI Top 100)",
   "type": "piechart",
   "description": "Source Packet + Destination Packet",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n dst_ip, src_ip, l4_proto, ndpi_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (src_sum+dst_sum) as src_dst\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, ndpi_proto, src_port , dst_port\nORDER BY src_dst desc limit 1000\n",
     "rawQuery": "SELECT\n dst_ip, src_ip, l4_proto, ndpi_proto, src_port, dst_port,\n sum(flow_dst_packets_processed) as dst_sum,\n sum(flow_src_packets_processed) as src_sum,\n (src_sum+dst_sum) as src_dst\nFROM Flow\nGROUP BY dst_ip, src_ip, l4_proto, ndpi_proto, src_port , dst_port\nORDER BY src_dst desc limit 1000",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Flow Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deamon",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "database": "information_schema",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT * FROM Daemon Limit 200\n\n",
       "rawQuery": "SELECT * FROM Daemon Limit 200",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "database": "Packet",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT \n   *\nFROM Flow\nlimit 200\n",
       "rawQuery": "SELECT \n   *\nFROM Flow\nlimit 200",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Error",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "database": "default",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    *\nFROM $table\n",
       "rawQuery": "SELECT\n    *\nFROM default.Error",
       "round": "0s",
       "table": "Error"
      }
     ]
    },
    {
     "title": "Packet",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    *\nFROM Packet\nlimit 200\n",
       "rawQuery": "SELECT\n    *\nFROM Packet\nlimit 200",
       "round": "0s"
      }
     ]
    }
   ]
  }
 ]
}